export enum Types {
  UPDATE_FILTER_MOVIES = "UPDATE_FILTER_MOVIES",
  UPDATE_VALUE = "UPDATE_VALUE",
  UPDATE_SORT = "UPDATE_SORT",
  UPDATE_TYPE_FILM = "UPDATE_TYPE_FILM",
  UPDATE_YEAR_FROM = "UPDATE_YEAR_FROM",
  UPDATE_YEAR_TO = "UPDATE_YEAR_TO",
  UPDATE_NUMBER_PAGE = "UPDATE_NUMBER_PAGE",
  RESET_NUMBER_PAGE = "RESET_NUMBER_PAGE",
  UPDATE_ID_FILM = "UPDATE_ID_FILM",
  CREATE_MINI_CARD = "CREATE_MINI_CARD",
}
